name: Build and Publish Wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-wheels:
    name: Build universal wheels (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"   # any stable version

      # Linux universal manylinux
      - name: Build wheels (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip -o dist
          manylinux: auto

      # mac
      - name: Build wheels (macOS)
        if: matrix.os == 'macos-latest'
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release --strip -o dist

      # windows
      - name: Install Rust (Windows)
        if: matrix.os == 'windows-latest'
        uses: dtolnay/rust-toolchain@stable

      - name: Install maturin (Windows)
        if: matrix.os == 'windows-latest'
        run: python -m pip install --upgrade pip maturin

      - name: Build wheels (Windows)
        if: matrix.os == 'windows-latest'
        run: maturin build --release --strip -o dist

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  publish:
    name: Publish to PyPI
    needs: build-wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') && github.repository == 'etsi-ai/etna'

    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist

      - run: |
          mkdir final_dist
          find dist -name "*.whl" -exec cp {} final_dist/ \;

      - run: |
          pip install maturin
          maturin publish --skip-existing final_dist/*.whl
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
